"""
dbt Backend
============
Code generation backend targeting dbt (data build tool).

Generates governed dbt models from an ExecutionPlan. Output includes:
- ``model.sql`` with dbt Jinja templating and governed SQL
- ``schema.yml`` with data quality tests derived from governance rules
- Partition configs, merge keys as uniqueness tests, PII annotations

Template-based — no LLM involved.
"""

from __future__ import annotations

from cfa.core.codegen import GeneratedCode
from cfa.core.planner import ExecutionPlan, ExecutionStep, StepType, WriteMode
from cfa.types import FaultSeverity
from cfa.validate.static import ForbiddenToken

from . import BackendAdapter, BackendCapabilities

_DBT_FORBIDDEN_TOKENS: list[ForbiddenToken] = [
    ForbiddenToken(pattern=r"\bDROP\s+TABLE\b", fault_code="STATIC_DBT_DROP_TABLE",
                   severity=FaultSeverity.CRITICAL,
                   message="DROP TABLE in governed dbt model forbidden.", is_regex=True),
    ForbiddenToken(pattern=r"\bDROP\s+DATABASE\b", fault_code="STATIC_DBT_DROP_DATABASE",
                   severity=FaultSeverity.CRITICAL,
                   message="DROP DATABASE in governed dbt model forbidden.", is_regex=True),
    ForbiddenToken(pattern=r"\bTRUNCATE\b", fault_code="STATIC_DBT_TRUNCATE",
                   severity=FaultSeverity.CRITICAL,
                   message="TRUNCATE forbidden in dbt governed models.", is_regex=True),
    ForbiddenToken(pattern=r"\bDELETE\s+FROM\b", fault_code="STATIC_DBT_DELETE",
                   severity=FaultSeverity.CRITICAL,
                   message="DELETE FROM forbidden in dbt governed models.", is_regex=True),
    ForbiddenToken(pattern=r"\bALTER\s+TABLE\b", fault_code="STATIC_DBT_ALTER_TABLE",
                   severity=FaultSeverity.HIGH,
                   message="ALTER TABLE forbidden — use dbt model rebuild.", is_regex=True),
]


class DbtBackend(BackendAdapter):
    """Generates governed dbt model + schema.yml from an ExecutionPlan."""

    def get_capabilities(self) -> BackendCapabilities:
        return BackendCapabilities(
            backend_name="dbt",
            backend_version="dbt-core-1.x",
            supports_merge=True,
            supports_partition_overwrite=True,
            supports_anonymization=True,
            supports_schema_enforcement=True,
            pii_anonymization_methods=["sha256", "drop", "md5", "tokenize"],
            cost_model_available=False,
            max_recommended_rows=500_000_000,
            supported_languages=["sql", "yaml"],
            forbidden_tokens=_DBT_FORBIDDEN_TOKENS,
        )

    def generate(self, plan: ExecutionPlan) -> GeneratedCode:
        sql_lines: list[str] = []
        schema_columns: list[dict[str, object]] = []
        model_name = self._derive_model_name(plan)
        pii_columns_anonymized: set[str] = set()
        merge_keys: list[str] = []
        partition_cols: list[str] = []
        step_code: dict[str, str] = {}
        ordered = plan.execution_order()

        for step in ordered:
            code = self._generate_step(step, plan)
            step_code[step.id] = code
            sql_lines.append(f"-- Step: {step.id} ({step.step_type.value})")
            sql_lines.append(code)
            sql_lines.append("")

            merge_keys = step.config.get("merge_keys", merge_keys)
            partition_cols = step.config.get("partition_by", partition_cols)
            if step.step_type == StepType.ANONYMIZE:
                for col in step.config.get("pii_columns", []):
                    pii_columns_anonymized.add(str(col))

        schema = self._build_schema_yml(
            model_name=model_name,
            plan=plan,
            merge_keys=merge_keys,
            partition_cols=partition_cols,
            pii_columns_anonymized=pii_columns_anonymized,
            schema_columns=schema_columns,
        )

        config_block = self._build_config(
            plan=plan,
            partition_cols=partition_cols,
            merge_keys=merge_keys,
        )

        full_body = "\n".join(sql_lines)
        model_sql = f"{config_block}\n\n{full_body}"

        combined = (
            f"-- dbt model: {model_name}\n"
            f"-- ============={'=' * len(model_name)}\n\n"
            f"{model_sql}\n\n"
            f"-- schema.yml (generated by CFA governance)\n"
            f"-- ==========================================\n\n"
            f"{schema}"
        )

        return GeneratedCode(
            plan_signature_hash=plan.signature_hash,
            intent_id=plan.intent_id,
            language="dbt",
            code=combined,
            step_code_map=step_code,
            metadata={
                "model_name": model_name,
                "write_mode": plan.write_mode.value,
                "consistency_unit": plan.consistency_unit.value,
                "step_count": plan.step_count,
            },
        )

    # ── Step generators ───────────────────────────────────────────────────

    def _generate_step(self, step: ExecutionStep, plan: ExecutionPlan) -> str:
        match step.step_type:
            case StepType.EXTRACT:
                return self._gen_extract(step)
            case StepType.ANONYMIZE:
                return self._gen_anonymize(step)
            case StepType.JOIN:
                return self._gen_join(step, plan)
            case StepType.AGGREGATE:
                return self._gen_aggregate(step)
            case StepType.LOAD:
                return self._gen_load(step, plan)
            case StepType.FILTER:
                return self._gen_filter(step)
            case StepType.TRANSFORM:
                return self._gen_transform(step)
            case _:
                return f"-- TODO: unsupported step type {step.step_type.value}"

    def _gen_extract(self, step: ExecutionStep) -> str:
        source = step.source or "unknown_source"
        model_ref = _ref_name(source)
        lines = [f"-- EXTRACT: {source}"]
        lines.append(f"SELECT * FROM {{{{ ref('{model_ref}') }}}}")

        filt = step.config.get("filter")
        if filt:
            col = _quote_ident(filt["column"])
            pred = filt["predicate"]
            lines.append(f"WHERE {col} {pred} '{{{{ var(\"date_param\") }}}}'")

        return "\n".join(lines)

    def _gen_anonymize(self, step: ExecutionStep) -> str:
        source = step.source or "source"
        pii_cols = step.config.get("pii_columns", [])
        strategy = step.config.get("strategy", "sha256")

        if not pii_cols:
            return f"-- No PII columns to anonymize for {source}"

        col_list = ", ".join(_quote_ident(c) for c in pii_cols)
        lines: list[str] = [
            f"-- ANONYMIZE: {source} (strategy={strategy}, columns={col_list})",
        ]
        for col in pii_cols:
            safe = _quote_ident(col)
            if strategy == "sha256":
                lines.append(f"--   {safe} replaced with SHA256({safe})")
            elif strategy == "drop":
                lines.append(f"--   {safe} dropped")
            else:
                lines.append(f"--   {safe} anonymized ({strategy})")
        return "\n".join(lines)

    def _gen_join(self, step: ExecutionStep, plan: ExecutionPlan) -> str:
        datasets = step.config.get("datasets", [])
        merge_keys = step.config.get("merge_keys", ["id"])

        if len(datasets) < 2:
            return "-- Join requires at least 2 datasets"

        left_alias = _cte_name(datasets[0])
        right_alias = _cte_name(datasets[1])
        left_ref = _ref_name(datasets[0])
        right_ref = _ref_name(datasets[1])
        on_clause = " AND ".join(
            f"{left_alias}.{_quote_ident(k)} = {right_alias}.{_quote_ident(k)}"
            for k in merge_keys
        )

        lines: list[str] = [f"-- JOIN: {datasets[0]} + {datasets[1]}"]
        lines.append(f"SELECT {left_alias}.*, {right_alias}.*")
        lines.append(f"FROM {{{{ ref('{left_ref}') }}}} {left_alias}")
        lines.append(f"INNER JOIN {{{{ ref('{right_ref}') }}}} {right_alias}")
        lines.append(f"  ON {on_clause}")

        return "\n".join(lines)

    def _gen_aggregate(self, step: ExecutionStep) -> str:
        group_by = step.config.get("group_by", [])
        lines: list[str] = ["-- AGGREGATE"]
        if not group_by:
            lines.append("SELECT COUNT(*) AS cnt FROM joined_cte")
        else:
            cols = ", ".join(_quote_ident(c) for c in group_by)
            lines.append(f"SELECT {cols}, COUNT(*) AS cnt")
            lines.append("FROM joined_cte")
            lines.append(f"GROUP BY {cols}")
        return "\n".join(lines)

    def _gen_load(self, step: ExecutionStep, plan: ExecutionPlan) -> str:
        target = step.target or "target_model"
        merge_keys = step.config.get("merge_keys", ["id"])
        partition_by = step.config.get("partition_by", [])

        lines: list[str] = [f"-- LOAD: {target}"]
        lines.append(f"--   Model: {{{{ ref('{_ref_name(target)}') }}}}")
        if merge_keys:
            lines.append(f"--   Merge keys: {', '.join(merge_keys)}")
        if partition_by:
            lines.append(f"--   Partition by: {', '.join(partition_by)}")
        lines.append("SELECT * FROM joined_cte")
        return "\n".join(lines)

    def _gen_filter(self, step: ExecutionStep) -> str:
        condition = step.config.get("condition", "1=1")
        return f"-- FILTER: WHERE {condition}"

    def _gen_transform(self, step: ExecutionStep) -> str:
        return f"-- TRANSFORM: {step.config}"

    # ── Config & schema generation ────────────────────────────────────────

    def _build_config(
        self,
        plan: ExecutionPlan,
        partition_cols: list[str],
        merge_keys: list[str],
    ) -> str:
        materialized = "table" if plan.write_mode == WriteMode.MERGE else "incremental"
        lines = [
            "{{ config(",
            f"    materialized='{materialized}',",
        ]
        if partition_cols:
            field_list = ", ".join(f"'{p}'" for p in partition_cols)
            lines.append(f"    partition_by={{'field': [{field_list}], 'data_type': 'date'}},")
        if merge_keys and plan.write_mode == WriteMode.MERGE:
            key_list = ", ".join(f"'{k}'" for k in merge_keys)
            lines.append(f"    unique_key=['{key_list}'],")
        lines.append(") }}")
        return "\n".join(lines)

    def _build_schema_yml(
        self,
        model_name: str,
        plan: ExecutionPlan,
        merge_keys: list[str],
        partition_cols: list[str],
        pii_columns_anonymized: set[str],
        schema_columns: list[dict[str, object]],
    ) -> str:
        lines = [
            "version: 2",
            "",
            "models:",
            f"  - name: {_ref_name(model_name)}",
            f'    description: "Governed model generated by CFA. Intent hash: {plan.signature_hash}"',
        ]

        columns: list[str] = list({
            str(k) for k in merge_keys
        } | {
            str(p) for p in partition_cols
        })

        if columns:
            lines.append("    columns:")
            for col in sorted(columns):
                lines.append(f"      - name: {_quote_ident(col)}")
                tests: list[str] = []
                if col in merge_keys:
                    tests.append("not_null")
                    if len(merge_keys) == 1:
                        tests.append("unique")
                if col in pii_columns_anonymized:
                    lines.append('        description: "PII column anonimizada via SHA256"')
                for test in tests:
                    lines.append("        tests:")
                    lines.append(f"          - {test}")

        if len(merge_keys) > 1:
            lines.append("    tests:")
            lines.append("      - dbt_utils.unique_combination_of_columns:")
            lines.append("          combination_of_columns:")
            for k in merge_keys:
                lines.append(f"            - {_quote_ident(k)}")

        return "\n".join(lines)

    @staticmethod
    def _derive_model_name(plan: ExecutionPlan) -> str:
        target = plan.write_mode.value
        domain = plan.metadata.get("domain", "governed")
        layer = plan.metadata.get("target_layer", "silver")
        return f"{layer}_{domain}_{target}"


# ── dbt-specific helpers ────────────────────────────────────────────────────


def _ref_name(source: str) -> str:
    clean = source.replace("-", "_").replace(".", "_").replace(" ", "_").lower()
    return clean


def _cte_name(source: str) -> str:
    clean = _ref_name(source)
    if len(clean) <= 8:
        return clean
    parts = clean.split("_")
    if len(parts) >= 2:
        return parts[0][:4] + "_" + parts[-1][:4]
    return clean[:8]


def _quote_ident(name: str) -> str:
    return str(name)


def _var_name(source: str) -> str:
    return f"cte_{_ref_name(source)}"
